variable "nic_name" {}
variable "location" {}
variable "resource_group_name" {}
variable "nsg_name" {}
variable "admin_password" {}
variable "admin_username" {}
variable "vmname" {}
variable "image_publisher" {}
variable "image_offer" {}
variable "image_sku" {}
variable "image_version" {}
variable "ip_configuration_name" {}
variable "subnet_name" {}
variable "vnet_name" {}